version: 2

project_name: tick

builds:
  - main: ./cmd/tick
    binary: tick
    ldflags:
      - -s -w
      - -X github.com/squeakycheese75/tick/internal/buildinfo.Version={{ .Version }}
      - -X github.com/squeakycheese75/tick/internal/buildinfo.Commit={{ .ShortCommit }}
      - -X github.com/squeakycheese75/tick/internal/buildinfo.BuildDate={{ .Date }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: squeakycheese75
    name: tick

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: '^feat'
    - title: Fixes
      regexp: '^fix'
    - title: Refactoring
      regexp: '^refactor'
    - title: Other
      regexp: '.*'

brews:
  - name: tick
    ids:
      - default
    repository:
      owner: squeakycheese75
      name: homebrew-tick
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/squeakycheese75/tick"
    description: "Terminal-native portfolio and market intelligence tool"
    license: "MIT"
    directory: Formula
    commit_author:
      name: James Wooltorton
      email: james_wooltorton@hotmail.com
    install: |
      bin.install "tick"
    test: |
      system "#{bin}/tick", "version"
