version: 2

project_name: tick

builds:
  - main: ./cmd/tick
    binary: tick
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: squeakycheese75
    name: tick

brews:
  - name: tick
    ids:
      - default
    repository:
      owner: squeakycheese75
      name: homebrew-tick
      branch: main
    homepage: "https://github.com/squeakycheese75/tick"
    description: "Terminal-native portfolio and market intelligence tool"
    license: "MIT"
    directory: Formula
    commit_author:
      name: James Wooltorton
      email: james_wooltorton@hotmail.com
    install: |
      bin.install "tick"