// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/squeakycheese75/tick/internal/usecase (interfaces: PortfolioRepository,InstrumentRepository,PositionRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_interfaces.go -package=mocks . PortfolioRepository,InstrumentRepository,PositionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/squeakycheese75/tick/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioRepository is a mock of PortfolioRepository interface.
type MockPortfolioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioRepositoryMockRecorder
	isgomock struct{}
}

// MockPortfolioRepositoryMockRecorder is the mock recorder for MockPortfolioRepository.
type MockPortfolioRepositoryMockRecorder struct {
	mock *MockPortfolioRepository
}

// NewMockPortfolioRepository creates a new mock instance.
func NewMockPortfolioRepository(ctrl *gomock.Controller) *MockPortfolioRepository {
	mock := &MockPortfolioRepository{ctrl: ctrl}
	mock.recorder = &MockPortfolioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioRepository) EXPECT() *MockPortfolioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortfolioRepository) Create(ctx context.Context, p repository.Portfolio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortfolioRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortfolioRepository)(nil).Create), ctx, p)
}

// GetByName mocks base method.
func (m *MockPortfolioRepository) GetByName(ctx context.Context, name string) (repository.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(repository.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPortfolioRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPortfolioRepository)(nil).GetByName), ctx, name)
}

// MockInstrumentRepository is a mock of InstrumentRepository interface.
type MockInstrumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentRepositoryMockRecorder
	isgomock struct{}
}

// MockInstrumentRepositoryMockRecorder is the mock recorder for MockInstrumentRepository.
type MockInstrumentRepositoryMockRecorder struct {
	mock *MockInstrumentRepository
}

// NewMockInstrumentRepository creates a new mock instance.
func NewMockInstrumentRepository(ctrl *gomock.Controller) *MockInstrumentRepository {
	mock := &MockInstrumentRepository{ctrl: ctrl}
	mock.recorder = &MockInstrumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentRepository) EXPECT() *MockInstrumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstrumentRepository) Create(ctx context.Context, p repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInstrumentRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstrumentRepository)(nil).Create), ctx, p)
}

// GetBySymbolAndExchange mocks base method.
func (m *MockInstrumentRepository) GetBySymbolAndExchange(ctx context.Context, symbol, exchange string) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbolAndExchange", ctx, symbol, exchange)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbolAndExchange indicates an expected call of GetBySymbolAndExchange.
func (mr *MockInstrumentRepositoryMockRecorder) GetBySymbolAndExchange(ctx, symbol, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbolAndExchange", reflect.TypeOf((*MockInstrumentRepository)(nil).GetBySymbolAndExchange), ctx, symbol, exchange)
}

// GetOrCreate mocks base method.
func (m *MockInstrumentRepository) GetOrCreate(ctx context.Context, in repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, in)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockInstrumentRepositoryMockRecorder) GetOrCreate(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockInstrumentRepository)(nil).GetOrCreate), ctx, in)
}

// MockPositionRepository is a mock of PositionRepository interface.
type MockPositionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPositionRepositoryMockRecorder
	isgomock struct{}
}

// MockPositionRepositoryMockRecorder is the mock recorder for MockPositionRepository.
type MockPositionRepositoryMockRecorder struct {
	mock *MockPositionRepository
}

// NewMockPositionRepository creates a new mock instance.
func NewMockPositionRepository(ctrl *gomock.Controller) *MockPositionRepository {
	mock := &MockPositionRepository{ctrl: ctrl}
	mock.recorder = &MockPositionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPositionRepository) EXPECT() *MockPositionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPositionRepository) Create(ctx context.Context, p repository.CreatePositionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPositionRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPositionRepository)(nil).Create), ctx, p)
}

// ListByPortfolioID mocks base method.
func (m *MockPositionRepository) ListByPortfolioID(ctx context.Context, portfolioID int64) ([]repository.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPortfolioID", ctx, portfolioID)
	ret0, _ := ret[0].([]repository.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPortfolioID indicates an expected call of ListByPortfolioID.
func (mr *MockPositionRepositoryMockRecorder) ListByPortfolioID(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPortfolioID", reflect.TypeOf((*MockPositionRepository)(nil).ListByPortfolioID), ctx, portfolioID)
}
