// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source internal/usecase/usecase.go -destination internal/usecase/mocks/mock_interfaces.go -package mocks . PortfolioRepository,InstrumentRepository,PositionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/tick/internal/domain"
	analysis "github.com/squeakycheese75/tick/internal/domain/analysis"
	instruments "github.com/squeakycheese75/tick/internal/instruments"
	repository "github.com/squeakycheese75/tick/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioRepository is a mock of PortfolioRepository interface.
type MockPortfolioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioRepositoryMockRecorder
	isgomock struct{}
}

// MockPortfolioRepositoryMockRecorder is the mock recorder for MockPortfolioRepository.
type MockPortfolioRepositoryMockRecorder struct {
	mock *MockPortfolioRepository
}

// NewMockPortfolioRepository creates a new mock instance.
func NewMockPortfolioRepository(ctrl *gomock.Controller) *MockPortfolioRepository {
	mock := &MockPortfolioRepository{ctrl: ctrl}
	mock.recorder = &MockPortfolioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioRepository) EXPECT() *MockPortfolioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortfolioRepository) Create(ctx context.Context, p repository.Portfolio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortfolioRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortfolioRepository)(nil).Create), ctx, p)
}

// GetByName mocks base method.
func (m *MockPortfolioRepository) GetByName(ctx context.Context, name string) (repository.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(repository.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPortfolioRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPortfolioRepository)(nil).GetByName), ctx, name)
}

// MockPositionRepository is a mock of PositionRepository interface.
type MockPositionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPositionRepositoryMockRecorder
	isgomock struct{}
}

// MockPositionRepositoryMockRecorder is the mock recorder for MockPositionRepository.
type MockPositionRepositoryMockRecorder struct {
	mock *MockPositionRepository
}

// NewMockPositionRepository creates a new mock instance.
func NewMockPositionRepository(ctrl *gomock.Controller) *MockPositionRepository {
	mock := &MockPositionRepository{ctrl: ctrl}
	mock.recorder = &MockPositionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPositionRepository) EXPECT() *MockPositionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPositionRepository) Create(ctx context.Context, p repository.CreatePositionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPositionRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPositionRepository)(nil).Create), ctx, p)
}

// ListByPortfolioID mocks base method.
func (m *MockPositionRepository) ListByPortfolioID(ctx context.Context, portfolioID int64) ([]repository.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPortfolioID", ctx, portfolioID)
	ret0, _ := ret[0].([]repository.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPortfolioID indicates an expected call of ListByPortfolioID.
func (mr *MockPositionRepositoryMockRecorder) ListByPortfolioID(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPortfolioID", reflect.TypeOf((*MockPositionRepository)(nil).ListByPortfolioID), ctx, portfolioID)
}

// MockInstrumentRepository is a mock of InstrumentRepository interface.
type MockInstrumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentRepositoryMockRecorder
	isgomock struct{}
}

// MockInstrumentRepositoryMockRecorder is the mock recorder for MockInstrumentRepository.
type MockInstrumentRepositoryMockRecorder struct {
	mock *MockInstrumentRepository
}

// NewMockInstrumentRepository creates a new mock instance.
func NewMockInstrumentRepository(ctrl *gomock.Controller) *MockInstrumentRepository {
	mock := &MockInstrumentRepository{ctrl: ctrl}
	mock.recorder = &MockInstrumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentRepository) EXPECT() *MockInstrumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstrumentRepository) Create(ctx context.Context, p repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInstrumentRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstrumentRepository)(nil).Create), ctx, p)
}

// GetBySymbolAndExchange mocks base method.
func (m *MockInstrumentRepository) GetBySymbolAndExchange(ctx context.Context, symbol, exchange string) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbolAndExchange", ctx, symbol, exchange)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbolAndExchange indicates an expected call of GetBySymbolAndExchange.
func (mr *MockInstrumentRepositoryMockRecorder) GetBySymbolAndExchange(ctx, symbol, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbolAndExchange", reflect.TypeOf((*MockInstrumentRepository)(nil).GetBySymbolAndExchange), ctx, symbol, exchange)
}

// GetOrCreate mocks base method.
func (m *MockInstrumentRepository) GetOrCreate(ctx context.Context, in repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, in)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockInstrumentRepositoryMockRecorder) GetOrCreate(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockInstrumentRepository)(nil).GetOrCreate), ctx, in)
}

// MockInstrumentResolver is a mock of InstrumentResolver interface.
type MockInstrumentResolver struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentResolverMockRecorder
	isgomock struct{}
}

// MockInstrumentResolverMockRecorder is the mock recorder for MockInstrumentResolver.
type MockInstrumentResolverMockRecorder struct {
	mock *MockInstrumentResolver
}

// NewMockInstrumentResolver creates a new mock instance.
func NewMockInstrumentResolver(ctrl *gomock.Controller) *MockInstrumentResolver {
	mock := &MockInstrumentResolver{ctrl: ctrl}
	mock.recorder = &MockInstrumentResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentResolver) EXPECT() *MockInstrumentResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockInstrumentResolver) Resolve(ctx context.Context, symbol string) (instruments.ResolvedInstrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, symbol)
	ret0, _ := ret[0].(instruments.ResolvedInstrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockInstrumentResolverMockRecorder) Resolve(ctx, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockInstrumentResolver)(nil).Resolve), ctx, symbol)
}

// MockPriceProvider is a mock of PriceProvider interface.
type MockPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderMockRecorder
	isgomock struct{}
}

// MockPriceProviderMockRecorder is the mock recorder for MockPriceProvider.
type MockPriceProviderMockRecorder struct {
	mock *MockPriceProvider
}

// NewMockPriceProvider creates a new mock instance.
func NewMockPriceProvider(ctrl *gomock.Controller) *MockPriceProvider {
	mock := &MockPriceProvider{ctrl: ctrl}
	mock.recorder = &MockPriceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceProvider) EXPECT() *MockPriceProviderMockRecorder {
	return m.recorder
}

// GetPrice mocks base method.
func (m *MockPriceProvider) GetPrice(ctx context.Context, ticker string) (float64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ctx, ticker)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockPriceProviderMockRecorder) GetPrice(ctx, ticker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockPriceProvider)(nil).GetPrice), ctx, ticker)
}

// MockFXProvider is a mock of FXProvider interface.
type MockFXProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFXProviderMockRecorder
	isgomock struct{}
}

// MockFXProviderMockRecorder is the mock recorder for MockFXProvider.
type MockFXProviderMockRecorder struct {
	mock *MockFXProvider
}

// NewMockFXProvider creates a new mock instance.
func NewMockFXProvider(ctrl *gomock.Controller) *MockFXProvider {
	mock := &MockFXProvider{ctrl: ctrl}
	mock.recorder = &MockFXProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFXProvider) EXPECT() *MockFXProviderMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockFXProvider) GetRate(ctx context.Context, from, to string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, from, to)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRate indicates an expected call of GetRate.
func (mr *MockFXProviderMockRecorder) GetRate(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockFXProvider)(nil).GetRate), ctx, from, to)
}

// MockPortfolioAnalyzer is a mock of PortfolioAnalyzer interface.
type MockPortfolioAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioAnalyzerMockRecorder
	isgomock struct{}
}

// MockPortfolioAnalyzerMockRecorder is the mock recorder for MockPortfolioAnalyzer.
type MockPortfolioAnalyzerMockRecorder struct {
	mock *MockPortfolioAnalyzer
}

// NewMockPortfolioAnalyzer creates a new mock instance.
func NewMockPortfolioAnalyzer(ctrl *gomock.Controller) *MockPortfolioAnalyzer {
	mock := &MockPortfolioAnalyzer{ctrl: ctrl}
	mock.recorder = &MockPortfolioAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioAnalyzer) EXPECT() *MockPortfolioAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockPortfolioAnalyzer) Analyze(ctx context.Context, in analysis.AnalyzePortfolioInput) (analysis.PortfolioAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, in)
	ret0, _ := ret[0].(analysis.PortfolioAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockPortfolioAnalyzerMockRecorder) Analyze(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockPortfolioAnalyzer)(nil).Analyze), ctx, in)
}

// MockRiskAnalyzer is a mock of RiskAnalyzer interface.
type MockRiskAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockRiskAnalyzerMockRecorder
	isgomock struct{}
}

// MockRiskAnalyzerMockRecorder is the mock recorder for MockRiskAnalyzer.
type MockRiskAnalyzerMockRecorder struct {
	mock *MockRiskAnalyzer
}

// NewMockRiskAnalyzer creates a new mock instance.
func NewMockRiskAnalyzer(ctrl *gomock.Controller) *MockRiskAnalyzer {
	mock := &MockRiskAnalyzer{ctrl: ctrl}
	mock.recorder = &MockRiskAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiskAnalyzer) EXPECT() *MockRiskAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockRiskAnalyzer) Analyze(in analysis.PortfolioAnalysis) (analysis.PortfolioRisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", in)
	ret0, _ := ret[0].(analysis.PortfolioRisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockRiskAnalyzerMockRecorder) Analyze(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockRiskAnalyzer)(nil).Analyze), in)
}

// MockNewsProvider is a mock of NewsProvider interface.
type MockNewsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNewsProviderMockRecorder
	isgomock struct{}
}

// MockNewsProviderMockRecorder is the mock recorder for MockNewsProvider.
type MockNewsProviderMockRecorder struct {
	mock *MockNewsProvider
}

// NewMockNewsProvider creates a new mock instance.
func NewMockNewsProvider(ctrl *gomock.Controller) *MockNewsProvider {
	mock := &MockNewsProvider{ctrl: ctrl}
	mock.recorder = &MockNewsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsProvider) EXPECT() *MockNewsProviderMockRecorder {
	return m.recorder
}

// GetNews mocks base method.
func (m *MockNewsProvider) GetNews(ctx context.Context, ticker string, limit int) ([]domain.NewsHeadline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNews", ctx, ticker, limit)
	ret0, _ := ret[0].([]domain.NewsHeadline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNews indicates an expected call of GetNews.
func (mr *MockNewsProviderMockRecorder) GetNews(ctx, ticker, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNews", reflect.TypeOf((*MockNewsProvider)(nil).GetNews), ctx, ticker, limit)
}

// MockPortfolioSvc is a mock of PortfolioSvc interface.
type MockPortfolioSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioSvcMockRecorder
	isgomock struct{}
}

// MockPortfolioSvcMockRecorder is the mock recorder for MockPortfolioSvc.
type MockPortfolioSvcMockRecorder struct {
	mock *MockPortfolioSvc
}

// NewMockPortfolioSvc creates a new mock instance.
func NewMockPortfolioSvc(ctrl *gomock.Controller) *MockPortfolioSvc {
	mock := &MockPortfolioSvc{ctrl: ctrl}
	mock.recorder = &MockPortfolioSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioSvc) EXPECT() *MockPortfolioSvcMockRecorder {
	return m.recorder
}

// GetAnalysis mocks base method.
func (m *MockPortfolioSvc) GetAnalysis(ctx context.Context, portfolioName string) (analysis.PortfolioAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalysis", ctx, portfolioName)
	ret0, _ := ret[0].(analysis.PortfolioAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalysis indicates an expected call of GetAnalysis.
func (mr *MockPortfolioSvcMockRecorder) GetAnalysis(ctx, portfolioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalysis", reflect.TypeOf((*MockPortfolioSvc)(nil).GetAnalysis), ctx, portfolioName)
}

// GetRisk mocks base method.
func (m *MockPortfolioSvc) GetRisk(ctx context.Context, portfolioName string) (analysis.PortfolioRisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRisk", ctx, portfolioName)
	ret0, _ := ret[0].(analysis.PortfolioRisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRisk indicates an expected call of GetRisk.
func (mr *MockPortfolioSvcMockRecorder) GetRisk(ctx, portfolioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRisk", reflect.TypeOf((*MockPortfolioSvc)(nil).GetRisk), ctx, portfolioName)
}

// MockPortfolioInsights is a mock of PortfolioInsights interface.
type MockPortfolioInsights struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioInsightsMockRecorder
	isgomock struct{}
}

// MockPortfolioInsightsMockRecorder is the mock recorder for MockPortfolioInsights.
type MockPortfolioInsightsMockRecorder struct {
	mock *MockPortfolioInsights
}

// NewMockPortfolioInsights creates a new mock instance.
func NewMockPortfolioInsights(ctrl *gomock.Controller) *MockPortfolioInsights {
	mock := &MockPortfolioInsights{ctrl: ctrl}
	mock.recorder = &MockPortfolioInsightsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioInsights) EXPECT() *MockPortfolioInsightsMockRecorder {
	return m.recorder
}

// AttentionSignals mocks base method.
func (m *MockPortfolioInsights) AttentionSignals(portfolioAnalysis analysis.PortfolioAnalysis, portfolioRisk analysis.PortfolioRisk) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttentionSignals", portfolioAnalysis, portfolioRisk)
	ret0, _ := ret[0].([]string)
	return ret0
}

// AttentionSignals indicates an expected call of AttentionSignals.
func (mr *MockPortfolioInsightsMockRecorder) AttentionSignals(portfolioAnalysis, portfolioRisk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttentionSignals", reflect.TypeOf((*MockPortfolioInsights)(nil).AttentionSignals), portfolioAnalysis, portfolioRisk)
}

// TopHoldings mocks base method.
func (m *MockPortfolioInsights) TopHoldings(portfolioAnalysis analysis.PortfolioAnalysis, limit int) []analysis.AnalyzedPosition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopHoldings", portfolioAnalysis, limit)
	ret0, _ := ret[0].([]analysis.AnalyzedPosition)
	return ret0
}

// TopHoldings indicates an expected call of TopHoldings.
func (mr *MockPortfolioInsightsMockRecorder) TopHoldings(portfolioAnalysis, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopHoldings", reflect.TypeOf((*MockPortfolioInsights)(nil).TopHoldings), portfolioAnalysis, limit)
}
