// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source internal/usecase/usecase.go -destination internal/usecase/mocks/mock_interfaces.go -package mocks . PortfolioRepository,InstrumentRepository,PositionRepository,InstrumentResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/squeakycheese75/tick/internal/domain"
	instruments "github.com/squeakycheese75/tick/internal/instruments"
	report "github.com/squeakycheese75/tick/internal/report"
	repository "github.com/squeakycheese75/tick/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioRepository is a mock of PortfolioRepository interface.
type MockPortfolioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioRepositoryMockRecorder
	isgomock struct{}
}

// MockPortfolioRepositoryMockRecorder is the mock recorder for MockPortfolioRepository.
type MockPortfolioRepositoryMockRecorder struct {
	mock *MockPortfolioRepository
}

// NewMockPortfolioRepository creates a new mock instance.
func NewMockPortfolioRepository(ctrl *gomock.Controller) *MockPortfolioRepository {
	mock := &MockPortfolioRepository{ctrl: ctrl}
	mock.recorder = &MockPortfolioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioRepository) EXPECT() *MockPortfolioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortfolioRepository) Create(ctx context.Context, p repository.Portfolio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortfolioRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortfolioRepository)(nil).Create), ctx, p)
}

// GetByName mocks base method.
func (m *MockPortfolioRepository) GetByName(ctx context.Context, name string) (repository.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(repository.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPortfolioRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPortfolioRepository)(nil).GetByName), ctx, name)
}

// MockPositionRepository is a mock of PositionRepository interface.
type MockPositionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPositionRepositoryMockRecorder
	isgomock struct{}
}

// MockPositionRepositoryMockRecorder is the mock recorder for MockPositionRepository.
type MockPositionRepositoryMockRecorder struct {
	mock *MockPositionRepository
}

// NewMockPositionRepository creates a new mock instance.
func NewMockPositionRepository(ctrl *gomock.Controller) *MockPositionRepository {
	mock := &MockPositionRepository{ctrl: ctrl}
	mock.recorder = &MockPositionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPositionRepository) EXPECT() *MockPositionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPositionRepository) Create(ctx context.Context, p repository.CreatePositionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPositionRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPositionRepository)(nil).Create), ctx, p)
}

// ListByPortfolioID mocks base method.
func (m *MockPositionRepository) ListByPortfolioID(ctx context.Context, portfolioID int64) ([]repository.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPortfolioID", ctx, portfolioID)
	ret0, _ := ret[0].([]repository.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPortfolioID indicates an expected call of ListByPortfolioID.
func (mr *MockPositionRepositoryMockRecorder) ListByPortfolioID(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPortfolioID", reflect.TypeOf((*MockPositionRepository)(nil).ListByPortfolioID), ctx, portfolioID)
}

// MockInstrumentRepository is a mock of InstrumentRepository interface.
type MockInstrumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentRepositoryMockRecorder
	isgomock struct{}
}

// MockInstrumentRepositoryMockRecorder is the mock recorder for MockInstrumentRepository.
type MockInstrumentRepositoryMockRecorder struct {
	mock *MockInstrumentRepository
}

// NewMockInstrumentRepository creates a new mock instance.
func NewMockInstrumentRepository(ctrl *gomock.Controller) *MockInstrumentRepository {
	mock := &MockInstrumentRepository{ctrl: ctrl}
	mock.recorder = &MockInstrumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentRepository) EXPECT() *MockInstrumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstrumentRepository) Create(ctx context.Context, p repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInstrumentRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstrumentRepository)(nil).Create), ctx, p)
}

// GetBySymbolAndExchange mocks base method.
func (m *MockInstrumentRepository) GetBySymbolAndExchange(ctx context.Context, symbol, exchange string) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbolAndExchange", ctx, symbol, exchange)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbolAndExchange indicates an expected call of GetBySymbolAndExchange.
func (mr *MockInstrumentRepositoryMockRecorder) GetBySymbolAndExchange(ctx, symbol, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbolAndExchange", reflect.TypeOf((*MockInstrumentRepository)(nil).GetBySymbolAndExchange), ctx, symbol, exchange)
}

// GetOrCreate mocks base method.
func (m *MockInstrumentRepository) GetOrCreate(ctx context.Context, in repository.Instrument) (repository.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, in)
	ret0, _ := ret[0].(repository.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockInstrumentRepositoryMockRecorder) GetOrCreate(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockInstrumentRepository)(nil).GetOrCreate), ctx, in)
}

// MockInstrumentResolver is a mock of InstrumentResolver interface.
type MockInstrumentResolver struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumentResolverMockRecorder
	isgomock struct{}
}

// MockInstrumentResolverMockRecorder is the mock recorder for MockInstrumentResolver.
type MockInstrumentResolverMockRecorder struct {
	mock *MockInstrumentResolver
}

// NewMockInstrumentResolver creates a new mock instance.
func NewMockInstrumentResolver(ctrl *gomock.Controller) *MockInstrumentResolver {
	mock := &MockInstrumentResolver{ctrl: ctrl}
	mock.recorder = &MockInstrumentResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumentResolver) EXPECT() *MockInstrumentResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockInstrumentResolver) Resolve(ctx context.Context, symbol string) (instruments.ResolvedInstrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, symbol)
	ret0, _ := ret[0].(instruments.ResolvedInstrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockInstrumentResolverMockRecorder) Resolve(ctx, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockInstrumentResolver)(nil).Resolve), ctx, symbol)
}

// MockPortfolioSnapshotRepository is a mock of PortfolioSnapshotRepository interface.
type MockPortfolioSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockPortfolioSnapshotRepositoryMockRecorder is the mock recorder for MockPortfolioSnapshotRepository.
type MockPortfolioSnapshotRepositoryMockRecorder struct {
	mock *MockPortfolioSnapshotRepository
}

// NewMockPortfolioSnapshotRepository creates a new mock instance.
func NewMockPortfolioSnapshotRepository(ctrl *gomock.Controller) *MockPortfolioSnapshotRepository {
	mock := &MockPortfolioSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockPortfolioSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioSnapshotRepository) EXPECT() *MockPortfolioSnapshotRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortfolioSnapshotRepository) Create(ctx context.Context, in repository.PortfolioSnapshot, positions []repository.PortfolioSnapshotPosition) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in, positions)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPortfolioSnapshotRepositoryMockRecorder) Create(ctx, in, positions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortfolioSnapshotRepository)(nil).Create), ctx, in, positions)
}

// GetLatestBefore mocks base method.
func (m *MockPortfolioSnapshotRepository) GetLatestBefore(ctx context.Context, portfolioName string, before time.Time) (repository.PortfolioSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBefore", ctx, portfolioName, before)
	ret0, _ := ret[0].(repository.PortfolioSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBefore indicates an expected call of GetLatestBefore.
func (mr *MockPortfolioSnapshotRepositoryMockRecorder) GetLatestBefore(ctx, portfolioName, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBefore", reflect.TypeOf((*MockPortfolioSnapshotRepository)(nil).GetLatestBefore), ctx, portfolioName, before)
}

// ListPositionsBySnapshotID mocks base method.
func (m *MockPortfolioSnapshotRepository) ListPositionsBySnapshotID(ctx context.Context, snapshotID int64) ([]repository.PortfolioSnapshotPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPositionsBySnapshotID", ctx, snapshotID)
	ret0, _ := ret[0].([]repository.PortfolioSnapshotPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositionsBySnapshotID indicates an expected call of ListPositionsBySnapshotID.
func (mr *MockPortfolioSnapshotRepositoryMockRecorder) ListPositionsBySnapshotID(ctx, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositionsBySnapshotID", reflect.TypeOf((*MockPortfolioSnapshotRepository)(nil).ListPositionsBySnapshotID), ctx, snapshotID)
}

// MockNewsSvc is a mock of NewsSvc interface.
type MockNewsSvc struct {
	ctrl     *gomock.Controller
	recorder *MockNewsSvcMockRecorder
	isgomock struct{}
}

// MockNewsSvcMockRecorder is the mock recorder for MockNewsSvc.
type MockNewsSvcMockRecorder struct {
	mock *MockNewsSvc
}

// NewMockNewsSvc creates a new mock instance.
func NewMockNewsSvc(ctrl *gomock.Controller) *MockNewsSvc {
	mock := &MockNewsSvc{ctrl: ctrl}
	mock.recorder = &MockNewsSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsSvc) EXPECT() *MockNewsSvcMockRecorder {
	return m.recorder
}

// GetNews mocks base method.
func (m *MockNewsSvc) GetNews(ctx context.Context, ticker string, limit int) (domain.NewsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNews", ctx, ticker, limit)
	ret0, _ := ret[0].(domain.NewsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNews indicates an expected call of GetNews.
func (mr *MockNewsSvcMockRecorder) GetNews(ctx, ticker, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNews", reflect.TypeOf((*MockNewsSvc)(nil).GetNews), ctx, ticker, limit)
}

// MockPortfolioSvc is a mock of PortfolioSvc interface.
type MockPortfolioSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioSvcMockRecorder
	isgomock struct{}
}

// MockPortfolioSvcMockRecorder is the mock recorder for MockPortfolioSvc.
type MockPortfolioSvcMockRecorder struct {
	mock *MockPortfolioSvc
}

// NewMockPortfolioSvc creates a new mock instance.
func NewMockPortfolioSvc(ctrl *gomock.Controller) *MockPortfolioSvc {
	mock := &MockPortfolioSvc{ctrl: ctrl}
	mock.recorder = &MockPortfolioSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioSvc) EXPECT() *MockPortfolioSvcMockRecorder {
	return m.recorder
}

// GetAnalysis mocks base method.
func (m *MockPortfolioSvc) GetAnalysis(ctx context.Context, portfolioName string) (domain.PortfolioAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalysis", ctx, portfolioName)
	ret0, _ := ret[0].(domain.PortfolioAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalysis indicates an expected call of GetAnalysis.
func (mr *MockPortfolioSvcMockRecorder) GetAnalysis(ctx, portfolioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalysis", reflect.TypeOf((*MockPortfolioSvc)(nil).GetAnalysis), ctx, portfolioName)
}

// GetRisk mocks base method.
func (m *MockPortfolioSvc) GetRisk(ctx context.Context, portfolioName string) (domain.PortfolioRisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRisk", ctx, portfolioName)
	ret0, _ := ret[0].(domain.PortfolioRisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRisk indicates an expected call of GetRisk.
func (mr *MockPortfolioSvcMockRecorder) GetRisk(ctx, portfolioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRisk", reflect.TypeOf((*MockPortfolioSvc)(nil).GetRisk), ctx, portfolioName)
}

// MockDailyReportSummarizer is a mock of DailyReportSummarizer interface.
type MockDailyReportSummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockDailyReportSummarizerMockRecorder
	isgomock struct{}
}

// MockDailyReportSummarizerMockRecorder is the mock recorder for MockDailyReportSummarizer.
type MockDailyReportSummarizerMockRecorder struct {
	mock *MockDailyReportSummarizer
}

// NewMockDailyReportSummarizer creates a new mock instance.
func NewMockDailyReportSummarizer(ctrl *gomock.Controller) *MockDailyReportSummarizer {
	mock := &MockDailyReportSummarizer{ctrl: ctrl}
	mock.recorder = &MockDailyReportSummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyReportSummarizer) EXPECT() *MockDailyReportSummarizerMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockDailyReportSummarizer) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockDailyReportSummarizerMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockDailyReportSummarizer)(nil).Enabled))
}

// Summarize mocks base method.
func (m *MockDailyReportSummarizer) Summarize(ctx context.Context, arg1 domain.DailyReport) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockDailyReportSummarizerMockRecorder) Summarize(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockDailyReportSummarizer)(nil).Summarize), ctx, arg1)
}

// MockReportBuilder is a mock of ReportBuilder interface.
type MockReportBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockReportBuilderMockRecorder
	isgomock struct{}
}

// MockReportBuilderMockRecorder is the mock recorder for MockReportBuilder.
type MockReportBuilderMockRecorder struct {
	mock *MockReportBuilder
}

// NewMockReportBuilder creates a new mock instance.
func NewMockReportBuilder(ctrl *gomock.Controller) *MockReportBuilder {
	mock := &MockReportBuilder{ctrl: ctrl}
	mock.recorder = &MockReportBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportBuilder) EXPECT() *MockReportBuilderMockRecorder {
	return m.recorder
}

// BuildDailyReport mocks base method.
func (m *MockReportBuilder) BuildDailyReport(ctx context.Context, in report.BuildDailyReportParams) (domain.DailyReportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildDailyReport", ctx, in)
	ret0, _ := ret[0].(domain.DailyReportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildDailyReport indicates an expected call of BuildDailyReport.
func (mr *MockReportBuilderMockRecorder) BuildDailyReport(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildDailyReport", reflect.TypeOf((*MockReportBuilder)(nil).BuildDailyReport), ctx, in)
}

// BuildMorningBriefReport mocks base method.
func (m *MockReportBuilder) BuildMorningBriefReport(ctx context.Context, in report.BuildMorningBriefReportParams) (domain.BriefReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildMorningBriefReport", ctx, in)
	ret0, _ := ret[0].(domain.BriefReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildMorningBriefReport indicates an expected call of BuildMorningBriefReport.
func (mr *MockReportBuilderMockRecorder) BuildMorningBriefReport(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildMorningBriefReport", reflect.TypeOf((*MockReportBuilder)(nil).BuildMorningBriefReport), ctx, in)
}

// MockPricingSvc is a mock of PricingSvc interface.
type MockPricingSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPricingSvcMockRecorder
	isgomock struct{}
}

// MockPricingSvcMockRecorder is the mock recorder for MockPricingSvc.
type MockPricingSvcMockRecorder struct {
	mock *MockPricingSvc
}

// NewMockPricingSvc creates a new mock instance.
func NewMockPricingSvc(ctrl *gomock.Controller) *MockPricingSvc {
	mock := &MockPricingSvc{ctrl: ctrl}
	mock.recorder = &MockPricingSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingSvc) EXPECT() *MockPricingSvcMockRecorder {
	return m.recorder
}

// GetValuationQuote mocks base method.
func (m *MockPricingSvc) GetValuationQuote(ctx context.Context, symbol, targetCurrency, instrumentCurrency, instrumentType string) (domain.ValuationQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuationQuote", ctx, symbol, targetCurrency, instrumentCurrency, instrumentType)
	ret0, _ := ret[0].(domain.ValuationQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValuationQuote indicates an expected call of GetValuationQuote.
func (mr *MockPricingSvcMockRecorder) GetValuationQuote(ctx, symbol, targetCurrency, instrumentCurrency, instrumentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuationQuote", reflect.TypeOf((*MockPricingSvc)(nil).GetValuationQuote), ctx, symbol, targetCurrency, instrumentCurrency, instrumentType)
}
