// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/analysis/analysis.go
//
// Generated by this command:
//
//	mockgen -source internal/domain/analysis/analysis.go -destination=internal/domain/analysis/mocks/mock_interfaces.go -package=mocks . PricingSvc
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/squeakycheese75/tick/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPricingSvc is a mock of PricingSvc interface.
type MockPricingSvc struct {
	ctrl     *gomock.Controller
	recorder *MockPricingSvcMockRecorder
	isgomock struct{}
}

// MockPricingSvcMockRecorder is the mock recorder for MockPricingSvc.
type MockPricingSvcMockRecorder struct {
	mock *MockPricingSvc
}

// NewMockPricingSvc creates a new mock instance.
func NewMockPricingSvc(ctrl *gomock.Controller) *MockPricingSvc {
	mock := &MockPricingSvc{ctrl: ctrl}
	mock.recorder = &MockPricingSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingSvc) EXPECT() *MockPricingSvcMockRecorder {
	return m.recorder
}

// GetValuationQuote mocks base method.
func (m *MockPricingSvc) GetValuationQuote(ctx context.Context, ticker, targetCurrency, instrumentCurrency, instrumentType string) (domain.ValuationQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuationQuote", ctx, ticker, targetCurrency, instrumentCurrency, instrumentType)
	ret0, _ := ret[0].(domain.ValuationQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValuationQuote indicates an expected call of GetValuationQuote.
func (mr *MockPricingSvcMockRecorder) GetValuationQuote(ctx, ticker, targetCurrency, instrumentCurrency, instrumentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuationQuote", reflect.TypeOf((*MockPricingSvc)(nil).GetValuationQuote), ctx, ticker, targetCurrency, instrumentCurrency, instrumentType)
}
