// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type FxCache struct {
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	Rate          float64   `json:"rate"`
	Source        string    `json:"source"`
	FetchedAt     time.Time `json:"fetched_at"`
}

type Instrument struct {
	ID             int64          `json:"id"`
	Symbol         string         `json:"symbol"`
	ProviderSymbol string         `json:"provider_symbol"`
	AssetType      string         `json:"asset_type"`
	Exchange       sql.NullString `json:"exchange"`
	QuoteCurrency  string         `json:"quote_currency"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Portfolio struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PortfolioSnapshot struct {
	ID            int64     `json:"id"`
	PortfolioName string    `json:"portfolio_name"`
	BaseCurrency  string    `json:"base_currency"`
	TotalValue    float64   `json:"total_value"`
	CapturedAt    time.Time `json:"captured_at"`
}

type PortfolioSnapshotPosition struct {
	ID                 int64     `json:"id"`
	SnapshotID         int64     `json:"snapshot_id"`
	Symbol             string    `json:"symbol"`
	Quantity           float64   `json:"quantity"`
	InstrumentCurrency string    `json:"instrument_currency"`
	QuotedPrice        float64   `json:"quoted_price"`
	FxRate             float64   `json:"fx_rate"`
	MarketValueBase    float64   `json:"market_value_base"`
	Weight             float64   `json:"weight"`
	CreatedAt          time.Time `json:"created_at"`
}

type Position struct {
	ID           int64     `json:"id"`
	InstrumentID int64     `json:"instrument_id"`
	PortfolioID  int64     `json:"portfolio_id"`
	Quantity     float64   `json:"quantity"`
	AvgCost      float64   `json:"avg_cost"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PriceCache struct {
	Ticker        string    `json:"ticker"`
	Price         float64   `json:"price"`
	PriceCurrency string    `json:"price_currency"`
	PreviousClose float64   `json:"previous_close"`
	Change        float64   `json:"change"`
	ChangePercent float64   `json:"change_percent"`
	Source        string    `json:"source"`
	FetchedAt     time.Time `json:"fetched_at"`
}
