// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Instrument struct {
	ID             int64          `json:"id"`
	Symbol         string         `json:"symbol"`
	ProviderSymbol string         `json:"provider_symbol"`
	AssetType      string         `json:"asset_type"`
	Exchange       sql.NullString `json:"exchange"`
	QuoteCurrency  string         `json:"quote_currency"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Portfolio struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Position struct {
	ID           int64     `json:"id"`
	InstrumentID int64     `json:"instrument_id"`
	PortfolioID  int64     `json:"portfolio_id"`
	Quantity     float64   `json:"quantity"`
	AvgCost      float64   `json:"avg_cost"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
