// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createInstrument = `-- name: CreateInstrument :one
INSERT INTO instruments (
  symbol,
  provider_symbol,
  asset_type,
  exchange,
  quote_currency
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateInstrumentParams struct {
	Symbol         string         `json:"symbol"`
	ProviderSymbol string         `json:"provider_symbol"`
	AssetType      string         `json:"asset_type"`
	Exchange       sql.NullString `json:"exchange"`
	QuoteCurrency  string         `json:"quote_currency"`
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createInstrument,
		arg.Symbol,
		arg.ProviderSymbol,
		arg.AssetType,
		arg.Exchange,
		arg.QuoteCurrency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPortfolio = `-- name: CreatePortfolio :exec
INSERT INTO portfolios (name, base_currency)
VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET
    base_currency = excluded.base_currency
`

type CreatePortfolioParams struct {
	Name         string `json:"name"`
	BaseCurrency string `json:"base_currency"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) error {
	_, err := q.db.ExecContext(ctx, createPortfolio, arg.Name, arg.BaseCurrency)
	return err
}

const createPortfolioSnapshot = `-- name: CreatePortfolioSnapshot :one
INSERT INTO portfolio_snapshots (
    portfolio_name,
    base_currency,
    total_value,
    captured_at
) VALUES (?, ?, ?, ?)
RETURNING id, portfolio_name, base_currency, total_value, captured_at
`

type CreatePortfolioSnapshotParams struct {
	PortfolioName string    `json:"portfolio_name"`
	BaseCurrency  string    `json:"base_currency"`
	TotalValue    float64   `json:"total_value"`
	CapturedAt    time.Time `json:"captured_at"`
}

func (q *Queries) CreatePortfolioSnapshot(ctx context.Context, arg CreatePortfolioSnapshotParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createPortfolioSnapshot,
		arg.PortfolioName,
		arg.BaseCurrency,
		arg.TotalValue,
		arg.CapturedAt,
	)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioName,
		&i.BaseCurrency,
		&i.TotalValue,
		&i.CapturedAt,
	)
	return i, err
}

const createPortfolioSnapshotPosition = `-- name: CreatePortfolioSnapshotPosition :one
INSERT INTO portfolio_snapshot_positions (
    snapshot_id,
    symbol,
    quantity,
    instrument_currency,
    quoted_price,
    fx_rate,
    market_value_base,
    weight
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, snapshot_id, symbol, quantity, instrument_currency, quoted_price, fx_rate, market_value_base, weight, created_at
`

type CreatePortfolioSnapshotPositionParams struct {
	SnapshotID         int64   `json:"snapshot_id"`
	Symbol             string  `json:"symbol"`
	Quantity           float64 `json:"quantity"`
	InstrumentCurrency string  `json:"instrument_currency"`
	QuotedPrice        float64 `json:"quoted_price"`
	FxRate             float64 `json:"fx_rate"`
	MarketValueBase    float64 `json:"market_value_base"`
	Weight             float64 `json:"weight"`
}

func (q *Queries) CreatePortfolioSnapshotPosition(ctx context.Context, arg CreatePortfolioSnapshotPositionParams) (PortfolioSnapshotPosition, error) {
	row := q.db.QueryRowContext(ctx, createPortfolioSnapshotPosition,
		arg.SnapshotID,
		arg.Symbol,
		arg.Quantity,
		arg.InstrumentCurrency,
		arg.QuotedPrice,
		arg.FxRate,
		arg.MarketValueBase,
		arg.Weight,
	)
	var i PortfolioSnapshotPosition
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Symbol,
		&i.Quantity,
		&i.InstrumentCurrency,
		&i.QuotedPrice,
		&i.FxRate,
		&i.MarketValueBase,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (
  instrument_id,
  portfolio_id,
  quantity,
  avg_cost,
  currency
) VALUES (
  ?, ?, ?, ?, ?
)
ON CONFLICT(portfolio_id, instrument_id) DO UPDATE SET
    quantity = excluded.quantity,
    avg_cost = excluded.avg_cost,
    currency = excluded.currency
`

type CreatePositionParams struct {
	InstrumentID int64   `json:"instrument_id"`
	PortfolioID  int64   `json:"portfolio_id"`
	Quantity     float64 `json:"quantity"`
	AvgCost      float64 `json:"avg_cost"`
	Currency     string  `json:"currency"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.InstrumentID,
		arg.PortfolioID,
		arg.Quantity,
		arg.AvgCost,
		arg.Currency,
	)
	return err
}

const getFXCacheByPair = `-- name: GetFXCacheByPair :one
SELECT
    base_currency,
    quote_currency,
    rate,
    source,
    fetched_at
FROM fx_cache
WHERE base_currency = ? AND quote_currency = ?
`

type GetFXCacheByPairParams struct {
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
}

func (q *Queries) GetFXCacheByPair(ctx context.Context, arg GetFXCacheByPairParams) (FxCache, error) {
	row := q.db.QueryRowContext(ctx, getFXCacheByPair, arg.BaseCurrency, arg.QuoteCurrency)
	var i FxCache
	err := row.Scan(
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const getInstrumentBySymbolAndExchange = `-- name: GetInstrumentBySymbolAndExchange :one
SELECT id, symbol, provider_symbol, asset_type, exchange, quote_currency, created_at, updated_at
FROM instruments
WHERE symbol = ? AND exchange = ?
`

type GetInstrumentBySymbolAndExchangeParams struct {
	Symbol   string         `json:"symbol"`
	Exchange sql.NullString `json:"exchange"`
}

func (q *Queries) GetInstrumentBySymbolAndExchange(ctx context.Context, arg GetInstrumentBySymbolAndExchangeParams) (Instrument, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentBySymbolAndExchange, arg.Symbol, arg.Exchange)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ProviderSymbol,
		&i.AssetType,
		&i.Exchange,
		&i.QuoteCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPortfolioSnapshot = `-- name: GetLatestPortfolioSnapshot :one
SELECT id, portfolio_name, base_currency, total_value, captured_at
FROM portfolio_snapshots
WHERE portfolio_name = ?
ORDER BY captured_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestPortfolioSnapshot(ctx context.Context, portfolioName string) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestPortfolioSnapshot, portfolioName)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioName,
		&i.BaseCurrency,
		&i.TotalValue,
		&i.CapturedAt,
	)
	return i, err
}

const getLatestPortfolioSnapshotBefore = `-- name: GetLatestPortfolioSnapshotBefore :one
SELECT id, portfolio_name, base_currency, total_value, captured_at
FROM portfolio_snapshots
WHERE portfolio_name = ?
  AND captured_at < ?
ORDER BY captured_at DESC, id DESC
LIMIT 1
`

type GetLatestPortfolioSnapshotBeforeParams struct {
	PortfolioName string    `json:"portfolio_name"`
	CapturedAt    time.Time `json:"captured_at"`
}

func (q *Queries) GetLatestPortfolioSnapshotBefore(ctx context.Context, arg GetLatestPortfolioSnapshotBeforeParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestPortfolioSnapshotBefore, arg.PortfolioName, arg.CapturedAt)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioName,
		&i.BaseCurrency,
		&i.TotalValue,
		&i.CapturedAt,
	)
	return i, err
}

const getPortfolioByName = `-- name: GetPortfolioByName :one
;

SELECT id, name, base_currency, created_at, updated_at
FROM portfolios
WHERE name = ?
`

func (q *Queries) GetPortfolioByName(ctx context.Context, name string) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByName, name)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceCacheByTicker = `-- name: GetPriceCacheByTicker :one
SELECT
    ticker,
    price,
    price_currency,
    previous_close,
    change,
    change_percent,
    source,
    fetched_at
FROM price_cache
WHERE ticker = ?
`

func (q *Queries) GetPriceCacheByTicker(ctx context.Context, ticker string) (PriceCache, error) {
	row := q.db.QueryRowContext(ctx, getPriceCacheByTicker, ticker)
	var i PriceCache
	err := row.Scan(
		&i.Ticker,
		&i.Price,
		&i.PriceCurrency,
		&i.PreviousClose,
		&i.Change,
		&i.ChangePercent,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const listPortfolioSnapshotPositionsBySnapshotID = `-- name: ListPortfolioSnapshotPositionsBySnapshotID :many
SELECT id, snapshot_id, symbol, quantity, instrument_currency, quoted_price, fx_rate, market_value_base, weight, created_at
FROM portfolio_snapshot_positions
WHERE snapshot_id = ?
ORDER BY symbol ASC
`

func (q *Queries) ListPortfolioSnapshotPositionsBySnapshotID(ctx context.Context, snapshotID int64) ([]PortfolioSnapshotPosition, error) {
	rows, err := q.db.QueryContext(ctx, listPortfolioSnapshotPositionsBySnapshotID, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioSnapshotPosition
	for rows.Next() {
		var i PortfolioSnapshotPosition
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Symbol,
			&i.Quantity,
			&i.InstrumentCurrency,
			&i.QuotedPrice,
			&i.FxRate,
			&i.MarketValueBase,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByPortfolio = `-- name: ListPositionsByPortfolio :many
SELECT
    p.instrument_id,
    pf.name,
    i.symbol,
    p.quantity,
    p.avg_cost,
    p.currency,
    i.asset_type,
    i.exchange,
    i.quote_currency
FROM positions AS p
JOIN portfolios AS pf ON p.portfolio_id = pf.id
JOIN instruments AS i ON p.instrument_id = i.id
WHERE p.portfolio_id = ?
ORDER BY i.symbol ASC
`

type ListPositionsByPortfolioRow struct {
	InstrumentID  int64          `json:"instrument_id"`
	Name          string         `json:"name"`
	Symbol        string         `json:"symbol"`
	Quantity      float64        `json:"quantity"`
	AvgCost       float64        `json:"avg_cost"`
	Currency      string         `json:"currency"`
	AssetType     string         `json:"asset_type"`
	Exchange      sql.NullString `json:"exchange"`
	QuoteCurrency string         `json:"quote_currency"`
}

func (q *Queries) ListPositionsByPortfolio(ctx context.Context, portfolioID int64) ([]ListPositionsByPortfolioRow, error) {
	rows, err := q.db.QueryContext(ctx, listPositionsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPositionsByPortfolioRow
	for rows.Next() {
		var i ListPositionsByPortfolioRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Name,
			&i.Symbol,
			&i.Quantity,
			&i.AvgCost,
			&i.Currency,
			&i.AssetType,
			&i.Exchange,
			&i.QuoteCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFXCache = `-- name: UpsertFXCache :exec
INSERT INTO fx_cache (
    base_currency,
    quote_currency,
    rate,
    source,
    fetched_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(base_currency, quote_currency) DO UPDATE SET
    rate = excluded.rate,
    source = excluded.source,
    fetched_at = excluded.fetched_at
`

type UpsertFXCacheParams struct {
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	Rate          float64   `json:"rate"`
	Source        string    `json:"source"`
	FetchedAt     time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertFXCache(ctx context.Context, arg UpsertFXCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertFXCache,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.Source,
		arg.FetchedAt,
	)
	return err
}

const upsertPriceCache = `-- name: UpsertPriceCache :exec
INSERT INTO price_cache (
    ticker,
    price,
    price_currency,
    previous_close,
    change,
    change_percent,
    source,
    fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticker) DO UPDATE SET
    price = excluded.price,
    price_currency = excluded.price_currency,
    previous_close = excluded.previous_close,
    change = excluded.change,
    change_percent = excluded.change_percent,
    source = excluded.source,
    fetched_at = excluded.fetched_at
`

type UpsertPriceCacheParams struct {
	Ticker        string    `json:"ticker"`
	Price         float64   `json:"price"`
	PriceCurrency string    `json:"price_currency"`
	PreviousClose float64   `json:"previous_close"`
	Change        float64   `json:"change"`
	ChangePercent float64   `json:"change_percent"`
	Source        string    `json:"source"`
	FetchedAt     time.Time `json:"fetched_at"`
}

func (q *Queries) UpsertPriceCache(ctx context.Context, arg UpsertPriceCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPriceCache,
		arg.Ticker,
		arg.Price,
		arg.PriceCurrency,
		arg.PreviousClose,
		arg.Change,
		arg.ChangePercent,
		arg.Source,
		arg.FetchedAt,
	)
	return err
}
