// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createInstrument = `-- name: CreateInstrument :one
INSERT INTO instruments (
  symbol,
  provider_symbol,
  asset_type,
  exchange,
  quote_currency
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateInstrumentParams struct {
	Symbol         string         `json:"symbol"`
	ProviderSymbol string         `json:"provider_symbol"`
	AssetType      string         `json:"asset_type"`
	Exchange       sql.NullString `json:"exchange"`
	QuoteCurrency  string         `json:"quote_currency"`
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createInstrument,
		arg.Symbol,
		arg.ProviderSymbol,
		arg.AssetType,
		arg.Exchange,
		arg.QuoteCurrency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPortfolio = `-- name: CreatePortfolio :exec
INSERT INTO portfolios (name, base_currency)
VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET
    base_currency = excluded.base_currency
`

type CreatePortfolioParams struct {
	Name         string `json:"name"`
	BaseCurrency string `json:"base_currency"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) error {
	_, err := q.db.ExecContext(ctx, createPortfolio, arg.Name, arg.BaseCurrency)
	return err
}

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (
  instrument_id,
  portfolio_id,
  quantity,
  avg_cost,
  currency
) VALUES (
  ?, ?, ?, ?, ?
)
ON CONFLICT(portfolio_id, instrument_id) DO UPDATE SET
    quantity = excluded.quantity,
    avg_cost = excluded.avg_cost,
    currency = excluded.currency
`

type CreatePositionParams struct {
	InstrumentID int64   `json:"instrument_id"`
	PortfolioID  int64   `json:"portfolio_id"`
	Quantity     float64 `json:"quantity"`
	AvgCost      float64 `json:"avg_cost"`
	Currency     string  `json:"currency"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.InstrumentID,
		arg.PortfolioID,
		arg.Quantity,
		arg.AvgCost,
		arg.Currency,
	)
	return err
}

const getInstrumentBySymbolAndExchange = `-- name: GetInstrumentBySymbolAndExchange :one
SELECT id, symbol, provider_symbol, asset_type, exchange, quote_currency, created_at, updated_at
FROM instruments
WHERE symbol = ? AND exchange = ?
`

type GetInstrumentBySymbolAndExchangeParams struct {
	Symbol   string         `json:"symbol"`
	Exchange sql.NullString `json:"exchange"`
}

func (q *Queries) GetInstrumentBySymbolAndExchange(ctx context.Context, arg GetInstrumentBySymbolAndExchangeParams) (Instrument, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentBySymbolAndExchange, arg.Symbol, arg.Exchange)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ProviderSymbol,
		&i.AssetType,
		&i.Exchange,
		&i.QuoteCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioByName = `-- name: GetPortfolioByName :one
;

SELECT id, name, base_currency, created_at, updated_at
FROM portfolios
WHERE name = ?
`

func (q *Queries) GetPortfolioByName(ctx context.Context, name string) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByName, name)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionsByPortfolio = `-- name: ListPositionsByPortfolio :many
SELECT
    p.instrument_id,
    pf.name,
    i.symbol,
    p.quantity,
    p.avg_cost,
    p.currency,
    i.asset_type,
    i.exchange,
    i.quote_currency
FROM positions AS p
JOIN portfolios AS pf ON p.portfolio_id = pf.id
JOIN instruments AS i ON p.instrument_id = i.id
WHERE p.portfolio_id = ?
ORDER BY i.symbol ASC
`

type ListPositionsByPortfolioRow struct {
	InstrumentID  int64          `json:"instrument_id"`
	Name          string         `json:"name"`
	Symbol        string         `json:"symbol"`
	Quantity      float64        `json:"quantity"`
	AvgCost       float64        `json:"avg_cost"`
	Currency      string         `json:"currency"`
	AssetType     string         `json:"asset_type"`
	Exchange      sql.NullString `json:"exchange"`
	QuoteCurrency string         `json:"quote_currency"`
}

func (q *Queries) ListPositionsByPortfolio(ctx context.Context, portfolioID int64) ([]ListPositionsByPortfolioRow, error) {
	rows, err := q.db.QueryContext(ctx, listPositionsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPositionsByPortfolioRow
	for rows.Next() {
		var i ListPositionsByPortfolioRow
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Name,
			&i.Symbol,
			&i.Quantity,
			&i.AvgCost,
			&i.Currency,
			&i.AssetType,
			&i.Exchange,
			&i.QuoteCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
